### ISSUE TITLE
Set Command or modify object doesn't work

### ISSUE THREAD

**Issue by shenoynag** [CheckPointSW/CheckPointAnsibleMgmtCollection#2]
Hi Team,

I tried using this code to automate cp Configuration. Code works fine with Creating new objects (Host, Network etc) and rules, But Modifying the existing object using set command doesn't work  

Here is my sample playbook:

---
- name: Demo7-playbook
  hosts: checkpoint
  connection: httpapi
  tasks:
    - name: add-network
      cp_mgmt_network:
        name: demonetwork21
        state: present
        subnet: 192.0.10.0
        subnet_mask: 255.255.255.0
        auto_publish_session: "True"
      vars:
        ansible_checkpoint_domain: "DMN1"
    - name: set-network
      cp_mgmt_network:
        color: green
        mask_length: "16"
        name: demonetwork21
        new_name: demonetwork22
        state: present
        subnet: 192.0.10.0
        auto_publish_session: "True"
      vars:
        ansible_checkpoint_domain: "DMN1"

And error message what I get is " Unsupported parameters for (CP_mgmt_network:) Module: new_name

**Comment by chkp-orso** [comment]
Hey @shenoynag  
Thanks for your question.
We don't support parameter new_name in the for the first version, we'r planing to support it in the future.
You can find the documentation for each Ansible module in https://docs.ansible.com/ansible/latest/modules/list_of_network_modules.html#check-point
Also please see in the README to see how you run a playbook against a collection instead of the "regular" Ansible.
Thanks, Or

**Comment by shenoynag** [comment]
My question was not about just New_name parameter, Even standard set-command to modify the network object fails. I am not sure it is issue with Checkpoint API itself or the way Plugin is written. 
Example: I have Already network Object Created in my Management Server with below Parameters :
Name: network4 
Subnet: 4.1.80.0
mask_length: 24

Now, I want to modify the Subnet associated with object from 4.1.80.0 to 4.1.81.0. Here is my sample playbook for this.

---
- name: demo1
  hosts: check_point
  connection: httpapi
  tasks:
    - name: set-network
      check_point.mgmt.cp_mgmt_network:
        name: network4
        subnet: 4.1.81.0
        mask_length: 24
        auto_publish_session: true
      vars:
        ansible_checkpoint_domain: "DMN1"

When I run this playbook, I get below Error. 
fatal: [192.168.10.110]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "auto_publish_session": true,
            "broadcast": null,
            "color": null,
            "comments": null,
            "details_level": null,
            "groups": null,
            "ignore_errors": null,
            "ignore_warnings": null,
            "mask_length": 24,
            "mask_length4": null,
            "mask_length6": null,
            "name": "network4",
            "nat_settings": null,
            "state": "present",
            "subnet": "4.1.81.0",
            "subnet4": null,
            "subnet6": null,
            "subnet_mask": null,
            "tags": null,
            "version": null,
            "wait_for_task": true
        }
    },
    "msg": "Checkpoint device returned error 500 with message {'code': 'generic_internal_error', 'message': 'Internal error. For more info search for incident [5f3c03a8-c7c8-4a52-9c96-2ce382d4a7be] in log file'}"
}

API Error log from Checkpoint Management Server.

--------------------------------------
2019-12-09 11:23:40,108  INFO org.apache.cxf.interceptor.LoggingInInterceptor.log:250 [qtp-293646526-21] - Inbound Message
----------------------------
ID: 12
Address: http://127.0.0.1:50276/web_api/equals
Encoding: ISO-8859-1
Http-Method: POST
Content-Type: application/json
Headers: {accept-encoding=[identity], connection=[keep-alive], Content-Length=[92], content-type=[application/json], Host=[127.0.0.1:50276], User-Agent=[Python-urllib/3.6], X-Chkp-Sid=[IP4gIhhQ9EpWy7lj4zRq6qmYE_kdIyEdJqiLszxZ6CU], X-Forwarded-For=[192.168.10.100], X-Forwarded-Host=[192.168.10.110:443], X-Forwarded-Host-Port=[443], X-Forwarded-Server=[192.168.10.110]}
Payload: {"type": "network", "params": {"name": "network4", "subnet": "4.1.81.0", "mask-length": 24}}
--------------------------------------
2019-12-09 11:23:40,130  WARN com.checkpoint.management.web_api_is.utils.helpers.RequestHeadersHelper.getMediaType_aroundBody6:9 [qtp-293646526-21] - No Accept header received. Falling back to default media type [application/json].
2019-12-09 11:23:40,131  INFO com.checkpoint.management.web_api_is.utils.helpers.ApiCache.<init>:21 [qtp-293646526-21] - Cache created and initialized
2019-12-09 11:23:40,132  INFO com.checkpoint.management.web_api.web_services.WebApiEntryPoint.logRequestedCommandInfo:51 [qtp-293646526-21] - Executing [equals] of version 1.3 (references 1)
2019-12-09 11:23:40,262 ERROR com.checkpoint.management.web_api.core.handler.commands.apis.commands.EqualsRequestHandler.executeImpl:196 [qtp-293646526-21] - com/checkpoint/management/web_api_is/utils/AnnotationsUtils.getGetterMethodsFromSpecificAnnotations(Ljava/lang/Object;Ljava/util/Iterator;)Ljava/util/List; (loaded from file:/opt/CPsuite-R80.20/fw1/api/lib/web_api_is.jar by WebAppClassLoader=Check Point Management Web API@ffffffff93c48fc3) called from class com.checkpoint.management.web_api.core.handler.commands.apis.commands.EqualsRequestHandler (loaded from file:/opt/CPsuite-R80.20/fw1/api/lib/web_api_management.jar by WebAppClassLoader=Check Point Management Web API@ffffffff93c48fc3).
java.lang.NoSuchMethodError: com/checkpoint/management/web_api_is/utils/AnnotationsUtils.getGetterMethodsFromSpecificAnnotations(Ljava/lang/Object;Ljava/util/Iterator;)Ljava/util/List; (loaded from file:/opt/CPsuite-R80.20/fw1/api/lib/web_api_is.jar by WebAppClassLoader=Check Point Management Web API@ffffffff93c48fc3) called from class com.checkpoint.management.web_api.core.handler.commands.apis.commands.EqualsRequestHandler (loaded from file:/opt/CPsuite-R80.20/fw1/api/lib/web_api_management.jar by WebAppClassLoader=Check Point Management Web API@ffffffff93c48fc3).
	at com.checkpoint.management.web_api.core.handler.commands.apis.commands.EqualsRequestHandler.isEqualsWithSpecificParameters(EqualsRequestHandler.java:54)
	at com.checkpoint.management.web_api.core.handler.commands.apis.commands.EqualsRequestHandler.executeImpl(EqualsRequestHandler.java:82)
	at com.checkpoint.management.web_api.core.handler.commands.apis.commands.EqualsRequestHandler.executeImpl(EqualsRequestHandler.java:32)
	at com.checkpoint.management.web_api.core.handler.commands.on_targets.BaseCommandRequestHandler.execute_aroundBody0(BaseCommandRequestHandler.java:3)
	at com.checkpoint.management.web_api.core.handler.commands.on_targets.BaseCommandRequestHandler$AjcClosure1.run(BaseCommandRequestHandler.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.checkpoint.management.web_api_is.aspects.logging.WebApiMethodLoggerAspect.aroundMethodLoggerTest(WebApiMethodLoggerAspect.java:13)
	at com.checkpoint.management.web_api.core.handler.commands.on_targets.BaseCommandRequestHandler.execute(BaseCommandRequestHandler.java:5)
	at com.checkpoint.management.web_api.core.handler.commands.apis.commands.EqualsRequestHandler.execute(EqualsRequestHandler.java:214)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:95)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at com.checkpoint.management.web_api_is.utils.WebApiReflectionUtils.invoke(WebApiReflectionUtils.java:7)
	at com.checkpoint.management.web_api.web_services.WebApiEntryPoint.postEntryPoint(WebApiEntryPoint.java:81)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:95)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:181)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:97)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:204)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:101)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:251)
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:171)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:293)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:212)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:755)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:268)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:686)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1494)
	at org.eclipse.jetty.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:247)
	at org.eclipse.jetty.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:210)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
	at com.checkpoint.management.web_api.core.filter.LogCustomDebugFieldFilter.doFilter(LogCustomDebugFieldFilter.java:19)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1474)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:499)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:428)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:255)
	at org.eclipse.jetty.server.handler.IPAccessHandler.handle(IPAccessHandler.java:203)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:370)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489)
	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:960)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1021)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Thread.java:785)
2019-12-09 11:23:40,264 ERROR com.checkpoint.management.web_api_is.exceptions.WebApiInternalException.logErrorMessageWithIncidentId:33 [qtp-293646526-21] - [ERROR] Incident [5f3c03a8-c7c8-4a52-9c96-2ce382d4a7be]: com/checkpoint/management/web_api_is/utils/AnnotationsUtils.getGetterMethodsFromSpecificAnnotations(Ljava/lang/Object;Ljava/util/Iterator;)Ljava/util/List; (loaded from file:/opt/CPsuite-R80.20/fw1/api/lib/web_api_is.jar by WebAppClassLoader=Check Point Management Web API@ffffffff93c48fc3) called from class com.checkpoint.management.web_api.core.handler.commands.apis.commands.EqualsRequestHandler (loaded from file:/opt/CPsuite-R80.20/fw1/api/lib/web_api_management.jar by WebAppClassLoader=Check Point Management Web API@ffffffff93c48fc3).
2019-12-09 11:23:40,264 ERROR com.checkpoint.management.web_api_is.exceptions.WebApiGeneralException.log:42 [qtp-293646526-21] - Error code: [GENERIC_INTERNAL_ERROR]
2019-12-09 11:23:40,265 ERROR com.checkpoint.management.web_api_is.exceptions.WebApiGeneralException.log:43 [qtp-293646526-21] - Error message: [Internal error. For more info search for incident [5f3c03a8-c7c8-4a52-9c96-2ce382d4a7be] in log file]
2019-12-09 11:23:40,265 ERROR com.checkpoint.management.web_api.utils.WebApiCommandExceptionUtils.getErrorReply:84 [qtp-293646526-21] - Internal error exception. Incident id: [5f3c03a8-c7c8-4a52-9c96-2ce382d4a7be]
2019-12-09 11:23:40,266 ERROR com.checkpoint.management.web_api.utils.WebApiCommandExceptionUtils.getErrorReply:94 [qtp-293646526-21] - 
com.checkpoint.management.web_api_is.exceptions.WebApiInternalException
	at com.checkpoint.management.web_api.core.handler.commands.apis.commands.EqualsRequestHandler.executeImpl(EqualsRequestHandler.java:240)
	at com.checkpoint.management.web_api.core.handler.commands.apis.commands.EqualsRequestHandler.executeImpl(EqualsRequestHandler.java:32)
	at com.checkpoint.management.web_api.core.handler.commands.on_targets.BaseCommandRequestHandler.execute_aroundBody0(BaseCommandRequestHandler.java:3)
	at com.checkpoint.management.web_api.core.handler.commands.on_targets.BaseCommandRequestHandler$AjcClosure1.run(BaseCommandRequestHandler.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.checkpoint.management.web_api_is.aspects.logging.WebApiMethodLoggerAspect.aroundMethodLoggerTest(WebApiMethodLoggerAspect.java:13)
	at com.checkpoint.management.web_api.core.handler.commands.on_targets.BaseCommandRequestHandler.execute(BaseCommandRequestHandler.java:5)
	at com.checkpoint.management.web_api.core.handler.commands.apis.commands.EqualsRequestHandler.execute(EqualsRequestHandler.java:214)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:95)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at com.checkpoint.management.web_api_is.utils.WebApiReflectionUtils.invoke(WebApiReflectionUtils.java:7)
	at com.checkpoint.management.web_api.web_services.WebApiEntryPoint.postEntryPoint(WebApiEntryPoint.java:81)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:95)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:181)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:97)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:204)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:101)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:251)
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:171)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:293)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:212)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:755)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:268)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:686)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1494)
	at org.eclipse.jetty.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:247)
	at org.eclipse.jetty.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:210)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
	at com.checkpoint.management.web_api.core.filter.LogCustomDebugFieldFilter.doFilter(LogCustomDebugFieldFilter.java:19)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1474)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:499)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:428)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:255)
	at org.eclipse.jetty.server.handler.IPAccessHandler.handle(IPAccessHandler.java:203)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:370)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489)
	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:960)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1021)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Thread.java:785)
2019-12-09 11:23:40,267  INFO com.checkpoint.management.web_api_is.utils.CsvFileWriterUtils.writeCsvLine:7 [qtp-293646526-21] - 2019-12-09,11:23:40 -0500,equals,FAILED,136
2019-12-09 11:23:40,268  INFO org.apache.cxf.interceptor.LoggingOutInterceptor.log:250 [qtp-293646526-21] - Outbound Message
---------------------------
ID: 12
Response-Code: 500
Content-Type: application/json
Headers: {Content-Type=[application/json], Date=[Mon, 09 Dec 2019 16:23:40 GMT]}
Payload: {
  "code" : "generic_internal_error",
  "message" : "Internal error. For more info search for incident [5f3c03a8-c7c8-4a52-9c96-2ce382d4a7be] in log file"
}
--------------------------------------

**Comment by chkp-orso** [comment]
Hey @shenoynag , I have a few questions in order to get a beeter view about your issue.
1. Can you please run on your machine "cpinfo -y all" and send me the output
2. Was there a playbook who worked for you?
3. Which version of the collection you use?

**Comment by shenoynag** [comment]
1. Here is My Cpinfo Result 
admin@192.168.10.110's password: 
Last login: Thu Dec 12 10:36:58 2019 from 192.168.10.2
CLINFR0771  Config lock is owned by admin. Use the command 'lock database override' to acquire the lock.
MDM1> cpinfo -y all

This is Check Point CPinfo Build 914000196 for GAIA
 Local host is not a Gateway
[IDA]
	No hotfixes..

[CPFC]
	No hotfixes..

[MGMT]
	HOTFIX_R80_20_JHF_T118_EQ_251_MAIN

[FW1]
	No hotfixes..

FW1 build number:
This is Check Point Security Management Server R80.20 - Build 082
This is Check Point's software version R80.20 - Build 257

[SecurePlatform]
	No hotfixes..

[NGXCMP]
	No hotfixes..

[EdgeCmp]
	No hotfixes..

[SFWCMP]
	No hotfixes..

[SFWR75CMP]
	No hotfixes..

[SFWR77CMP]
	No hotfixes..

[FLICMP]
	No hotfixes..

[R75CMP]
	No hotfixes..

[R7520CMP]
	No hotfixes..

[R7540CMP]
	No hotfixes..

[R76CMP]
	No hotfixes..

[R77CMP]
	No hotfixes..

[PROVIDER-1]
	No hotfixes..

[Reporting Module]
	No hotfixes..

[SmartLog]
	No hotfixes..

[CPinfo]
	No hotfixes..

[VSEC]
	No hotfixes..

[DIAG]
	No hotfixes..

[MGMTAPI]
	No hotfixes..

[CPUpdates]
	BUNDLE_CPINFO	Take:  49


MDM1> 
=======
2. Yes new Object or host Creation Play book worked for me.
name: demo1
hosts: check_point
connection: httpapi
tasks:
name: add-network
check_point.mgmt.cp_mgmt_network:
name: network4
subnet: 4.1.81.0
mask_length: 24
auto_publish_session: true
vars:
ansible_checkpoint_domain: "DMN1"

3. Ansible Galaxy version : 1.0.2

**Comment by chkp-orso** [comment]
Hey,
I see now what's the problem.
You need to install R80.20 jumbo take 118 on the machine from this link: https://supportcenter.checkpoint.com/supportcenter/portal?eventSubmit_doGoviewsolutiondetails=&solutionid=sk137592#Availability

This is because the hotfix is based on the jumbo take 118

please contact us if something isn't working

Thanks, Or
