### ISSUE TITLE
ConnectionError for check_point.mgmt.cp_mgmt_access_layer_facts with RearOnly user rights

### ISSUE THREAD

**Issue by vmi-cloud** [CheckPointSW/CheckPointAnsibleMgmtCollection#49]
Hello,

we are getting error when collecting `access_layer_facts` (the same issue is for other *_facts modules):
```
TASK [Gather total number of access-layers objects] *************************************************************************************************************************************************************
task path: /home/vacmille/ansible/checkpoint-rights.yml:37
<inventory_hostname> attempting to start connection
<inventory_hostname> using connection plugin httpapi
<inventory_hostname> found existing local domain socket, using it!
<inventory_hostname> updating play_context for connection
<inventory_hostname>
<inventory_hostname> local domain socket path is /home/vacmille/.ansible/pc/5aec7a4b38
<inventory_hostname> ESTABLISH LOCAL CONNECTION FOR USER: vacmille
<inventory_hostname> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/vacmille/.ansible/tmp/ansible-local-24075FEWsGv `"&& mkdir "` echo /home/vacmille/.ansible/tmp/ansible-local-24075FEWsGv/ansible-tmp-1639991818.3-24130-44292744810870 `" && echo ansible-tmp-1639991818.3-24130-44292744810870="` echo /home/vacmille/.ansible/tmp/ansible-local-24075FEWsGv/ansible-tmp-1639991818.3-24130-44292744810870 `" ) && sleep 0'
Using module file /home/vacmille/ansible/collections/ansible_collections/check_point/mgmt/plugins/modules/cp_mgmt_access_layer_facts.py
<inventory_hostname> PUT /home/vacmille/.ansible/tmp/ansible-local-24075FEWsGv/tmpcsM640 TO /home/vacmille/.ansible/tmp/ansible-local-24075FEWsGv/ansible-tmp-1639991818.3-24130-44292744810870/AnsiballZ_cp_mgmt_access_layer_facts.py
<inventory_hostname> EXEC /bin/sh -c 'chmod u+x /home/vacmille/.ansible/tmp/ansible-local-24075FEWsGv/ansible-tmp-1639991818.3-24130-44292744810870/ /home/vacmille/.ansible/tmp/ansible-local-24075FEWsGv/ansible-tmp-1639991818.3-24130-44292744810870/AnsiballZ_cp_mgmt_access_layer_facts.py && sleep 0'
<inventory_hostname> EXEC /bin/sh -c '/usr/bin/python /home/vacmille/.ansible/tmp/ansible-local-24075FEWsGv/ansible-tmp-1639991818.3-24130-44292744810870/AnsiballZ_cp_mgmt_access_layer_facts.py && sleep 0'
<inventory_hostname> EXEC /bin/sh -c 'rm -f -r /home/vacmille/.ansible/tmp/ansible-local-24075FEWsGv/ansible-tmp-1639991818.3-24130-44292744810870/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/home/vacmille/.ansible/tmp/ansible-local-24075FEWsGv/ansible-tmp-1639991818.3-24130-44292744810870/AnsiballZ_cp_mgmt_access_layer_facts.py", line 102, in <module>
    _ansiballz_main()
  File "/home/vacmille/.ansible/tmp/ansible-local-24075FEWsGv/ansible-tmp-1639991818.3-24130-44292744810870/AnsiballZ_cp_mgmt_access_layer_facts.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/vacmille/.ansible/tmp/ansible-local-24075FEWsGv/ansible-tmp-1639991818.3-24130-44292744810870/AnsiballZ_cp_mgmt_access_layer_facts.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.check_point.mgmt.plugins.modules.cp_mgmt_access_layer_facts', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib64/python2.7/runpy.py", line 176, in run_module
    fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/tmp/ansible_check_point.mgmt.cp_mgmt_access_layer_facts_payload_da1nrW/ansible_check_point.mgmt.cp_mgmt_access_layer_facts_payload.zip/ansible_collections/check_point/mgmt/plugins/modules/cp_mgmt_access_layer_facts.py", line 126, in <module>
  File "/tmp/ansible_check_point.mgmt.cp_mgmt_access_layer_facts_payload_da1nrW/ansible_check_point.mgmt.cp_mgmt_access_layer_facts_payload.zip/ansible_collections/check_point/mgmt/plugins/modules/cp_mgmt_access_layer_facts.py", line 121, in main
  File "/tmp/ansible_check_point.mgmt.cp_mgmt_access_layer_facts_payload_da1nrW/ansible_check_point.mgmt.cp_mgmt_access_layer_facts_payload.zip/ansible_collections/check_point/mgmt/plugins/module_utils/checkpoint.py", line 240, in api_call_facts
  File "/tmp/ansible_check_point.mgmt.cp_mgmt_access_layer_facts_payload_da1nrW/ansible_check_point.mgmt.cp_mgmt_access_layer_facts_payload.zip/ansible_collections/check_point/mgmt/plugins/module_utils/checkpoint.py", line 191, in handle_call
  File "/tmp/ansible_check_point.mgmt.cp_mgmt_access_layer_facts_payload_da1nrW/ansible_check_point.mgmt.cp_mgmt_access_layer_facts_payload.zip/ansible_collections/check_point/mgmt/plugins/module_utils/checkpoint.py", line 65, in send_request
  File "/tmp/ansible_check_point.mgmt.cp_mgmt_access_layer_facts_payload_da1nrW/ansible_check_point.mgmt.cp_mgmt_access_layer_facts_payload.zip/ansible/module_utils/connection.py", line 185, in __rpc__
ansible.module_utils.connection.ConnectionError: Server returned response without token info during connection authentication: 400
fatal: [prgdca-sd-mds]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/vacmille/.ansible/tmp/ansible-local-24075FEWsGv/ansible-tmp-1639991818.3-24130-44292744810870/AnsiballZ_cp_mgmt_access_layer_facts.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/vacmille/.ansible/tmp/ansible-local-24075FEWsGv/ansible-tmp-1639991818.3-24130-44292744810870/AnsiballZ_cp_mgmt_access_layer_facts.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/vacmille/.ansible/tmp/ansible-local-24075FEWsGv/ansible-tmp-1639991818.3-24130-44292744810870/AnsiballZ_cp_mgmt_access_layer_facts.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.check_point.mgmt.plugins.modules.cp_mgmt_access_layer_facts', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python2.7/runpy.py\", line 176, in run_module\n    fname, loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", line 82, in _run_module_code\n    mod_name, mod_fname, mod_loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/tmp/ansible_check_point.mgmt.cp_mgmt_access_layer_facts_payload_da1nrW/ansible_check_point.mgmt.cp_mgmt_access_layer_facts_payload.zip/ansible_collections/check_point/mgmt/plugins/modules/cp_mgmt_access_layer_facts.py\", line 126, in <module>\n  File \"/tmp/ansible_check_point.mgmt.cp_mgmt_access_layer_facts_payload_da1nrW/ansible_check_point.mgmt.cp_mgmt_access_layer_facts_payload.zip/ansible_collections/check_point/mgmt/plugins/modules/cp_mgmt_access_layer_facts.py\", line 121, in main\n  File \"/tmp/ansible_check_point.mgmt.cp_mgmt_access_layer_facts_payload_da1nrW/ansible_check_point.mgmt.cp_mgmt_access_layer_facts_payload.zip/ansible_collections/check_point/mgmt/plugins/module_utils/checkpoint.py\", line 240, in api_call_facts\n  File \"/tmp/ansible_check_point.mgmt.cp_mgmt_access_layer_facts_payload_da1nrW/ansible_check_point.mgmt.cp_mgmt_access_layer_facts_payload.zip/ansible_collections/check_point/mgmt/plugins/module_utils/checkpoint.py\", line 191, in handle_call\n  File \"/tmp/ansible_check_point.mgmt.cp_mgmt_access_layer_facts_payload_da1nrW/ansible_check_point.mgmt.cp_mgmt_access_layer_facts_payload.zip/ansible_collections/check_point/mgmt/plugins/module_utils/checkpoint.py\", line 65, in send_request\n  File \"/tmp/ansible_check_point.mgmt.cp_mgmt_access_layer_facts_payload_da1nrW/ansible_check_point.mgmt.cp_mgmt_access_layer_facts_payload.zip/ansible/module_utils/connection.py\", line 185, in __rpc__\nansible.module_utils.connection.ConnectionError: Server returned response without token info during connection authentication: 400\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

while running playbook with user that has Read-Only rights:
```
---
- name: Colect data from Checkpoint management
  hosts: check_point
  connection: httpapi
  gather_facts: no

  collections:
  - check_point.mgmt

  vars:
    ansible_checkpoint_domain: EMEA-DC

  tasks:
  - name: Print domain working on
    ansible.builtin.debug:
      msg: "{{ ansible_checkpoint_domain }}"
    when:
      - ansible_checkpoint_domain is defined

  - name: Gather total number of access-layers objects
    check_point.mgmt.cp_mgmt_access_layer_facts:
      details_level: uid
    register: access_layers_temp
```

The playbook is running when we add wright rights to user. 
**Read only rights has to be sufficient for fact gathering modules.**

We verified the same functionality collecting data over API as documented at https://sc1.checkpoint.com/documents/latest/APIs/#web/show-access-layer~v1.8%20
and the API request using Read-Only user was processed correctly.

Thank you in advance for correcting this user authentication issue.

Kind regards,
Vaclav

**Comment by chkp-shirango** [comment]
Hi @vmi-cloud,

Thanks for reaching us.
We will fix this in the next version.

Thanks,
Shiran

**Comment by vmi-cloud** [comment]
Hi @chkp-shirango ,
Thank you for information. Looking forward for next version.
Kind regards,
Vaclav

**Comment by vmi-cloud** [comment]
hello @chkp-shirango
I would like to ask you, what is the resolution status? I do not see any link to code change that is resolving the issue with rights requirement.
Kind regards,
Vaclav
