### ISSUE TITLE
nameless rules in rule base prevent use of `cp_mgmt_access_rule`

### ISSUE THREAD

**Issue by 2ps** [CheckPointSW/CheckPointAnsibleMgmtCollection#68]
The checkpoint smart console allows access rules without names.  When working with an existing rule base that has access rules without names, the `cp_mgmt_access_rule` module fails when looping through the rules in the rule base trying to get the rule position number by name since the `name` key will not exist in the `rules` dictionary.  

```
  module_stderr: |-
    Traceback (most recent call last):
      File "<stdin>", line 102, in <module>
      File "<stdin>", line 94, in _ansiballz_main
      File "<stdin>", line 40, in invoke_module
      File "/usr/lib/python3.6/runpy.py", line 205, in run_module
        return _run_module_code(code, init_globals, run_name, mod_spec)
      File "/usr/lib/python3.6/runpy.py", line 96, in _run_module_code
        mod_name, mod_spec, pkg_name, script_name)
      File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "/tmp/ansible_cp_mgmt_access_rule_payload_5wzew0zj/ansible_cp_mgmt_access_rule_payload.zip/ansible_collections/check_point/mgmt/plugins/modules/cp_mgmt_access_rule.py", line 373, in <module>
      File "/tmp/ansible_cp_mgmt_access_rule_payload_5wzew0zj/ansible_cp_mgmt_access_rule_payload.zip/ansible_collections/check_point/mgmt/plugins/modules/cp_mgmt_access_rule.py", line 367, in main
      File "/tmp/ansible_cp_mgmt_access_rule_payload_5wzew0zj/ansible_cp_mgmt_access_rule_payload.zip/ansible_collections/check_point/mgmt/plugins/module_utils/checkpoint.py", line 515, in api_call_for_rule
      File "/tmp/ansible_cp_mgmt_access_rule_payload_5wzew0zj/ansible_cp_mgmt_access_rule_payload.zip/ansible_collections/check_point/mgmt/plugins/module_utils/checkpoint.py", line 486, in is_equals_with_all_params
      File "/tmp/ansible_cp_mgmt_access_rule_payload_5wzew0zj/ansible_cp_mgmt_access_rule_payload.zip/ansible_collections/check_point/mgmt/plugins/module_utils/checkpoint.py", line 430, in is_equals_with_position_param
      File "/tmp/ansible_cp_mgmt_access_rule_payload_5wzew0zj/ansible_cp_mgmt_access_rule_payload.zip/ansible_collections/check_point/mgmt/plugins/module_utils/checkpoint.py", line 387, in get_number_from_position
    ValueError: invalid literal for int() with base 10: "{'below': 'my_awesome_rule'}"
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1
```

**Comment by chkp-edenbr** [comment]
Hi,
Our Ansible modules require a unique name identifier.
Regards,
Eden
